// Database types are auto-generated by Prisma
// Run: pnpm db:generate

// Import types from Prisma Client:
// import { Group, Participant, Assignment, Exclusion, User } from '@prisma/client'

// For convenience, re-export some common types
export type * from '@prisma/client'


