import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Starting seed...')

  // Create a demo draw
  const draw = await prisma.draw.create({
    data: {
      name: 'Family Christmas 2025',
      adminToken: 'demo-admin-token-12345', // In production, use crypto.randomUUID()
      budget: '$20-$50',
      exchangeDate: new Date('2025-12-25'),
      customMessage: `Welcome to our Secret Santa! 🎅

Rules:
- Budget: $20-$50
- Exchange date: December 25th
- Be creative and have fun!

Remember to check your wishlist and send some hints to build anticipation!`,
      rules: '1. Be thoughtful\n2. Respect the budget\n3. Keep it a secret!',
      isComplete: false,
      emailsSent: false,
    },
  })

  console.log('✅ Created draw:', draw.name)
  console.log(`📋 Admin URL: /admin/${draw.adminToken}`)

  // Create demo participants with unique tokens
  const participantsData = [
    { name: 'John Doe 🎄', email: 'john@example.com', token: 'john-token-uuid-1' },
    { name: 'Jane Doe', email: 'jane@example.com', token: 'jane-token-uuid-2' },
    { name: 'Bob Smith', email: 'bob@example.com', token: 'bob-token-uuid-3' },
    { name: 'Alice Smith 🎁', email: 'alice@example.com', token: 'alice-token-uuid-4' },
    { name: 'Charlie Brown', email: 'charlie@example.com', token: 'charlie-token-uuid-5' },
  ]

  const createdParticipants = []
  for (const pData of participantsData) {
    const participant = await prisma.participant.create({
      data: {
        ...pData,
        drawId: draw.id,
        wishlist: `Hi! I'm ${pData.name}. Here's what I like:\n- Books (mystery, sci-fi)\n- Coffee accessories\n- Plants\n- Cozy socks`,
      },
    })
    createdParticipants.push(participant)
    console.log(`✅ Created participant: ${participant.name}`)
    console.log(`   🔗 Panel URL: /participant/${participant.token}`)
  }

  // Create exclusions for couples (John & Jane, Bob & Alice)
  await prisma.exclusion.createMany({
    data: [
      {
        drawId: draw.id,
        participant1Id: createdParticipants[0].id, // John
        participant2Id: createdParticipants[1].id, // Jane
        reason: 'couple',
      },
      {
        drawId: draw.id,
        participant1Id: createdParticipants[2].id, // Bob
        participant2Id: createdParticipants[3].id, // Alice
        reason: 'couple',
      },
    ],
  })

  console.log('✅ Created 2 exclusions for couples')

  // Optional: Create sample assignments (for testing)
  // NOTE: In production, these are generated by the algorithm
  await prisma.assignment.createMany({
    data: [
      { drawId: draw.id, giverId: createdParticipants[0].id, receiverId: createdParticipants[2].id }, // John → Bob
      { drawId: draw.id, giverId: createdParticipants[1].id, receiverId: createdParticipants[4].id }, // Jane → Charlie
      { drawId: draw.id, giverId: createdParticipants[2].id, receiverId: createdParticipants[1].id }, // Bob → Jane
      { drawId: draw.id, giverId: createdParticipants[3].id, receiverId: createdParticipants[0].id }, // Alice → John
      { drawId: draw.id, giverId: createdParticipants[4].id, receiverId: createdParticipants[3].id }, // Charlie → Alice
    ],
  })

  console.log('✅ Created sample assignments')

  // Update draw to mark as complete
  await prisma.draw.update({
    where: { id: draw.id },
    data: {
      isComplete: true,
      assignmentDate: new Date(),
    },
  })

  // Create a sample hint
  await prisma.hint.create({
    data: {
      drawId: draw.id,
      senderToken: createdParticipants[0].token, // John
      receiverToken: createdParticipants[2].token, // Bob (John's assigned person)
      message: '🎁 Hint #1: It\'s something you can use every morning...',
      emailSent: false,
    },
  })

  console.log('✅ Created sample hint')
  console.log('🎉 Seed completed!')
  console.log('\n📝 Test URLs:')
  console.log(`   Admin: /admin/${draw.adminToken}`)
  participantsData.forEach((p) => {
    console.log(`   ${p.name}: /participant/${p.token}`)
  })
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })

